spring.application.name=auth-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/freelance_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:94a08da1fecbb6e8b46990538c7b50b2c153e7f59d4c1fbc4469d4d5eb6e50e994a08da1fecbb6e8b46990538c7b50b2c153e7f59d4c1fbc4469d4d5eb6e50e9}
jwt.expiration=${JWT_EXPIRATION:86400000}
