apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
  - port: 8080        # cluster port
    targetPort: 5001  # container port (IMPORTANT)