pipeline {
    agent any

    environment {
        IMAGE_NAME = "yashodaadarsh/payment-service"
        GIT_REPO = "https://github.com/yashodaadarsh/GigFlow.git"
        GIT_BRANCH = "devops"
        SERVICE = "payment-service"
        DEPLOYMENT_NAME = "payment-service-app-deployment"
    }

    stages {

        stage('Checkout from GitHub') {
            steps {
                deleteDir()
                git branch: "${GIT_BRANCH}", url: "${GIT_REPO}"
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("backend/${SERVICE}") {
                    sh '''
                    docker build -t ${SERVICE}:${BUILD_NUMBER} .
                    docker tag ${SERVICE}:${BUILD_NUMBER} ${IMAGE_NAME}:${BUILD_NUMBER}
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push ${IMAGE_NAME}:${BUILD_NUMBER}
                    docker logout
                    '''
                }
            }
        }

        stage('Delete the Image') {
            steps {
                sh '''
                echo "Deleting local Docker images..."

                docker rmi ${SERVICE}:${BUILD_NUMBER} || true
                docker rmi ${IMAGE_NAME}:${BUILD_NUMBER} || true

                echo "Cleaning dangling images..."
                docker image prune -f

                echo "Cleanup done"
                '''
            }
        }

        stage('Update Kubernetes Manifest') {
            steps {
                dir("backend/${SERVICE}") {
                    sh '''
                    sed -i "s|image: .*|image: ${IMAGE_NAME}:${BUILD_NUMBER}|g" k8s/deployment.yaml
                    '''
                }
            }
        }

        stage('Commit & Push Manifest to GitHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'github-creds',
                    usernameVariable: 'GIT_USER',
                    passwordVariable: 'GIT_PASS'
                )]) {
                    dir("backend/${SERVICE}") {
                        sh '''
                        git config user.name "jenkins"
                        git config user.email "jenkins@example.com"

                        git add k8s/deployment.yaml

                        git commit -m "Updated image to ${BUILD_NUMBER}" || echo "No changes to commit"

                        git push https://${GIT_USER}:${GIT_PASS}@github.com/yashodaadarsh/GigFlow.git ${GIT_BRANCH}
                        '''
                    }
                }
            }
        }

        stage('Apply Kubernetes Resources') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                    dir("backend/${SERVICE}") {
                        sh '''
                        export KUBECONFIG=$KUBECONFIG

                        echo "Applying Service..."
                        kubectl apply -f k8s/service.yaml

                        echo "Applying Secret..."
                        kubectl apply -f k8s/dbsecret.yaml

                        echo "Applying Deployment..."
                        kubectl apply -f k8s/deployment.yaml

                        echo "Resources applied successfully"
                        '''
                    }
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                    sh '''
                    export KUBECONFIG=$KUBECONFIG

                    echo "Checking nodes..."
                    kubectl get nodes

                    echo "Checking pods..."
                    kubectl get pods

                    echo "Checking rollout..."
                    kubectl rollout status deployment/${DEPLOYMENT_NAME}
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "✅ Deployment successful!"
        }
        failure {
            echo "❌ Pipeline failed! Check logs."
        }
    }
    
}