# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend-app-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: frontend-app
#   template:
#     metadata:
#       labels:
#         app: frontend-app
#     spec:
#       containers:
#       - name: frontend-app
#         image: yashodaadarsh/frontend-service:8
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 5173


apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: yashodaadarsh/frontend-service:2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80