apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fontend-app
  template:
    metadata:
      labels:
        app: fontend-app
    spec:
      containers:
      - name: fontend-app
        image: yashodaadarsh/my-k8s-cicd-app:latest  # your Docker Hub image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080