apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: yashodaadarsh/frontend-service:8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173