apiVersion: apps/v1
kind: Deployment
metadata:
  name: gig-service-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gig-service
  template:
    metadata:
      labels:
        app: gig-service
    spec:
      containers:
      - name: gig-service
        image: yashodaadarsh/gig-service:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080