apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
      - name: ml-service
        image: yashodaadarsh/ml-recommendation-service:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000